# Generated by Django 2.2.1 on 2019-05-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20190522_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='lasttname',
            new_name='lastname',
        ),
    ]
