# Generated by Django 2.2.1 on 2019-05-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test decription sirflhjrslifhjrepif oirhgoirfvg pr9fv9 p9ifeprog '),
            preserve_default=False,
        ),
    ]
