# Generated by Django 2.2.1 on 2019-05-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_auto_20190525_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='Sample Image', upload_to=''),
            preserve_default=False,
        ),
    ]
