# Generated by Django 2.2.1 on 2019-05-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_order_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='Sample Image', upload_to=''),
            preserve_default=False,
        ),
    ]
