# Generated by Django 2.2.1 on 2019-05-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='additional_info',
            field=models.CharField(default='This is default additional info ', max_length=1000),
            preserve_default=False,
        ),
    ]
